import {Token, TokenType} from './types.ts';

interface ASTNode {
    type: TokenType;
    children?: ASTNode[];
    value?: string;
    attributes?: Record<string, string|number|boolean>;
}

/**
 * The Parser class is responsible for converting a stream of Tokens into an Abstract Syntax Tree (AST).
 * It processes the tokens generated by the Lexer and structures them into a hierarchy.
 */
class Parser {
    /**
     * Parses an array of tokens into an AST.
     * @param tokens The array of tokens produced by the Lexer.
     * @returns The root node of the AST (usually a BODY node).
     */
    parse(tokens: Token[]): ASTNode {
        const root: ASTNode = {type: TokenType.BODY, children: []};

        for (const token of tokens) {
            const node: ASTNode = this.parseToken(token);
            root.children!.push(node);
        }

        return root;
    }


    /**
     * Extracts attributes from a token to be stored in the AST node.
     * This converts token properties (like depth, href, lang) into a generic attributes object.
     * @param token The token to extract attributes from.
     * @returns A record of attributes or undefined if none exist.
     */
    private extractAttributes(token: Token): Record<string, any> | undefined {
        const entries = Object.entries(token);
        // const attrs = this.attributeKeys.reduce((acc, key) => {
        //     if (token[key] !== undefined) {
        //         acc[key] = token[key];
        //     }
        //     return acc;
        // }, {} as Record<string, any>);
        if (entries.length === 0) {
            return undefined;
        }
        return Object.fromEntries(entries);
    }

    /**
     * Converts a single Token into an ASTNode.
     * Recursively processes child tokens if they exist.
     * @param token The token to parse.
     * @returns The corresponding ASTNode.
     */
    private parseToken(token: Token): ASTNode {
        // Recursively process nested tokens
        if (token.tokens) {
            return {
                type: token.type,
                children: token.tokens.map(t => this.parseToken(t)),
                attributes: this.extractAttributes(token),
            };
        }

        return {
            type: token.type,
            value: token.text || '',
            attributes: this.extractAttributes(token),
        };
    }
}

export {Parser};
export type {ASTNode}